flags:
  text:
    integer-simple: false
packages:
- '.'
extra-deps:
- async-2.0.2
- cereal-0.5.1.0
- exceptions-0.8.0.2
- fsnotify-0.2.1
- hfsevents-0.1.6
- mtl-2.2.1
- stm-2.4.4
- system-filepath-0.4.13.4
- temporary-1.2.0.3
- text-1.2.1.3
- transformers-compat-0.4.0.4
- unix-compat-0.4.1.4
- dlist-0.7.1.2
- Glob-0.7.5
- pureMD5-2.1.2.1
- crypto-api-0.13.2
- tagged-0.8.2
- entropy-0.3.7
- ansi-terminal-0.6.2.3
resolver: ghc-7.10
